export const LOGIN  = "LOGIN";
export const LOGOUT = "LOGOUT";

export const CURRENT_USER_LOADING = "CURRENT_USER_LOADING";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_ERROR   = "CURRENT_USER_ERROR";

export const LEAD_COURSES_LOADING   = "LEAD_COURSES_LOADING";
export const LEAD_COURSES_SUCCESS   = "LEAD_COURSES_SUCCESS";
export const LEAD_COURSES_ERROR     = "LEAD_COURSES_ERROR";

export const TESTS_SCHEMAS_LOADING   = "TESTS_SCHEMAS_LOADING";
export const TESTS_SCHEMAS_SUCCESS   = "TESTS_SCHEMAS_SUCCESS";
export const TESTS_SCHEMAS_ERROR     = "TESTS_SCHEMAS_ERROR";

export const TEST_SCHEMA_LOADING     = "TEST_SCHEMA_LOADING";
export const TEST_SCHEMA_SUCCESS     = "TEST_SCHEMA_SUCCESS";
export const TEST_SCHEMA_ERROR       = "TEST_SCHEMA_ERROR";

export const SUBJECTS_LOADING   = "SUBJECTS_LOADING";
export const SUBJECTS_SUCCESS   = "SUBJECTS_SUCCESS";
export const SUBJECTS_ERROR     = "SUBJECTS_ERROR";

export const COURSE_LOADING   = "COURSE_LOADING";
export const COURSE_SUCCESS   = "COURSE_SUCCESS";
export const COURSE_ERROR     = "COURSE_ERROR";