export const LOGIN  = "LOGIN";
export const LOGOUT = "LOGOUT";

export const CURRENT_USER_LOADING = "CURRENT_USER_LOADING";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_ERROR   = "CURRENT_USER_ERROR";

export const LEAD_COURSES_LOADING   = "LEAD_COURSES_LOADING";
export const LEAD_COURSES_SUCCESS   = "LEAD_COURSES_SUCCESS";
export const LEAD_COURSES_ERROR     = "LEAD_COURSES_ERROR";